export const CONTACTS = [
	{
		id: "1",
		lastName: "Adams",
		firstName: "Caroline",
		phone: "4695937963",
		department: "Science/Coach",
		room: "B102",
		email: "Caroline.Adams@risd.org",
	},
	{
		id: "2",
		lastName: "Anderson",
		firstName: "Kelli",
		phone: "4695937947",
		department: "HUM",
		room: "A201",
		email: "Kelli.Anderson@risd.org",
	},
	{
		id: "3",
		lastName: "Andrews",
		firstName: "Delaney",
		phone: "4695937993",
		department: "SLP",
		room: "A225",
		email: "Delaney.Andrews@risd.org",
	},
	{
		id: "4",
		lastName: "Ayers",
		firstName: "Sonya",
		phone: "4695937941",
		department: "Dyslexia",
		room: "A110",
		email: "Sonya.Ayers@risd.org",
	},
	{
		id: "5",
		lastName: "Baskeyfield",
		firstName: "Brian",
		phone: "4695937953",
		department: "PE/Coach",
		room: "LGYM",
		email: "Brian.Baskeyfield@risd.org",
	},
	{
		id: "6",
		lastName: "Beck",
		firstName: "Tawna",
		phone: "4695937960",
		department: "French",
		room: "A207",
		email: "Tawna.Beck-Davis@risd.org",
	},
	{
		id: "7",
		lastName: "Becker",
		firstName: "David",
		phone: "4695938010",
		department: "Band",
		room: "BAND",
		email: "David.Becker@risd.org",
	},
	{
		id: "8",
		lastName: "Bishop",
		firstName: "Karen",
		phone: "4695938013",
		department: "DP Aide",
		room: "B102",
		email: "Karen.Bishop@risd.org",
	},
	{
		id: "9",
		lastName: "Bisquera",
		firstName: "Jenelle",
		phone: "4695937943",
		department: "HUM",
		room: "A217",
		email: "Jenelle.Bisquera@risd.org",
	},
	{
		id: "10",
		lastName: "Brantley",
		firstName: "Amanda",
		phone: "4695937919",
		department: "IC STEAM",
		room: "A108",
		email: "Amanda.Brantley@risd.org",
	},
	{
		id: "11",
		lastName: "Braxton",
		firstName: "Leonard",
		phone: "4695938033",
		department: "L-Z AP",
		room: "OFFICE",
		email: "Leonard.Braxton@risd.org",
	},
	{
		id: "12",
		lastName: "Brzozowski",
		firstName: "Jill",
		phone: "4695937929",
		department: "SpEd ELA",
		room: "A210",
		email: "Jill.Brzozowski@risd.org",
	},
	{
		id: "13",
		lastName: "Bunch",
		firstName: "Tiffany",
		phone: "4695997934",
		department: "HUM",
		room: "A104",
		email: "Tiffany.Bunch@risd.org",
	},
	{
		id: "14",
		lastName: "Caravano",
		firstName: "Kate",
		phone: "4695938020",
		department: "Math",
		room: "B107",
		email: "Kathryn.Caravano@risd.org",
	},
	{
		id: "15",
		lastName: "Cardenas",
		firstName: "Dinina",
		phone: "4695937902",
		department: "ISS",
		room: "A109",
		email: "Dinia.Cardenas@risd.org",
	},
	{
		id: "16",
		lastName: "Cervantez",
		firstName: "Michelle",
		phone: "4695937906",
		department: "Front Off. Sec.",
		room: "OFFICE",
		email: "Michelle.Cervantes@risd.org",
	},
	{
		id: "17",
		lastName: "Chapa, Jr.",
		firstName: "Gerald",
		phone: "4695937944",
		department: "SpEd Math",
		room: "A209",
		email: "Gerald.Chapa@risd.org",
	},
	{
		id: "18",
		lastName: "Chase",
		firstName: "Jackie",
		phone: "4695938021",
		department: "AVID",
		room: "C103",
		email: "Jacqueline.Chase@risd.org",
	},
	{
		id: "19",
		lastName: "Chong",
		firstName: "Ana",
		phone: "4695938005",
		department: "SDS",
		room: "A121",
		email: "Ana.Chong@risd.org",
	},
	{
		id: "20",
		lastName: "Dees",
		firstName: "Jacob",
		phone: "4695937995",
		department: "Digital Coach",
		room: "A103",
		email: "Jacob.Dees@risd.org",
	},
	{
		id: "21",
		lastName: "Dees",
		firstName: "Kaitlin",
		phone: "4695937937",
		department: "Math",
		room: "B103",
		email: "Kaitlin.Dees@risd.org",
	},
	{
		id: "22",
		lastName: "Dorsey",
		firstName: "Tiffany",
		phone: "4695938027",
		department: "Science",
		room: "A218",
		email: "Tiffany.Dorsey@risd.org",
	},
	{
		id: "23",
		lastName: "Evans",
		firstName: "Taylor M.",
		phone: "4695938010",
		department: "Band",
		room: "BAND",
		email: "Taylor.Evans@risd.org",
	},
	{
		id: "24",
		lastName: "Flores",
		firstName: "NIna",
		phone: "4695938031",
		department: "Exec. Asst.",
		room: "OFFICE",
		email: "Nina.Flores@risd.org",
	},
	{
		id: "25",
		lastName: "Foster",
		firstName: "Flora",
		phone: "4695938023",
		department: "SPED DLC",
		room: "B104",
		email: "Flora.Foster@risd.org",
	},
	{
		id: "26",
		lastName: "Gainey",
		firstName: "Sandra",
		phone: "4695937933",
		department: "SPED",
		room: "OFF",
		email: "Sandra.Gainey@risd.org",
	},
	{
		id: "27",
		lastName: "Gaither",
		firstName: "Yolanda",
		phone: "4695938030",
		department: "Principal",
		room: "OFFICE",
		email: "Yolanda.Gaither@risd.org",
	},
	{
		id: "28",
		lastName: "Garibaldi",
		firstName: "Peter",
		phone: "4695937921",
		department: "AVID/Coach",
		room: "C105",
		email: "Peter.Garibaldi@risd.org",
	},
	{
		id: "29",
		lastName: "Goldfarb",
		firstName: "Abby",
		phone: "4695937936",
		department: "HUM",
		room: "A202",
		email: "Abby.Goldfarb@risd.org",
	},
	{
		id: "30",
		lastName: "Gonzalez",
		firstName: "Lyna",
		phone: "4695937979",
		department: "Library",
		room: "LIBRARY",
		email: "Lyna.Gonzalez@risd.org",
	},
	{
		id: "31",
		lastName: "Gould",
		firstName: "Sarah",
		phone: "4695937924",
		department: "IC Math/Sci.",
		room: "A108",
		email: "Sarah.Gould@risd.org",
	},
	{
		id: "32",
		lastName: "Graham",
		firstName: "Jonathan",
		phone: "4695937970",
		department: "SPED DLC",
		room: "B104",
		email: "Jonathan.Graham@risd.org",
	},
	{
		id: "33",
		lastName: "Griffin",
		firstName: "Artra",
		phone: "4695937964",
		department: "AVID",
		room: "B111",
		email: "Artra.Griffin@risd.org",
	},
	{
		id: "34",
		lastName: "Harvey",
		firstName: "ShaDarrion",
		phone: "4695938018",
		department: "Math",
		room: "B108",
		email: "ShaDarrion.Harvey@risd.org",
	},
	{
		id: "35",
		lastName: "Horn",
		firstName: "Kelsey",
		phone: "4695937951",
		department: "Math",
		room: "B108",
		email: "Kelsey.Horn@risd.org",
	},
	{
		id: "36",
		lastName: "Hushfield",
		firstName: "Leigh Ann",
		phone: "4695937940",
		department: "Science",
		room: "A213",
		email: "Leigh.Hushfield@risd.org",
	},
	{
		id: "37",
		lastName: "Irizarry-Colon",
		firstName: "Sofia",
		phone: "4695937942",
		department: "Spanish",
		room: "A205",
		email: "Sofia.Irizarry-Colon@risd.org",
	},
	{
		id: "38",
		lastName: "Jordan",
		firstName: "Laura",
		phone: "4695937948",
		department: "Girls PE/Health",
		room: "B110",
		email: "Laura.Jordan@risd.org",
	},
	{
		id: "39",
		lastName: "Lagos",
		firstName: "Alejandra",
		phone: "4695937973",
		department: "SpEd Aide",
		room: "B104",
		email: "Alejandra.Lagos@risd.org",
	},
	{
		id: "40",
		lastName: "Landry",
		firstName: "Keosha",
		phone: "4695937978",
		department: "Library Aide",
		room: "LIBRARY",
		email: "Keosha.Landry@risd.org",
	},
	{
		id: "41",
		lastName: "Ledgerwood",
		firstName: "Stephanie",
		phone: "4695937914",
		department: "SRO",
		room: "A107",
		email: "Stefanie.Ledgerwood@risd.org",
	},
	{
		id: "42",
		lastName: "Martel",
		firstName: "Meghan",
		phone: "4695937980",
		department: "Art",
		room: "B109",
		email: "Meghan.Martel@risd.org",
	},
	{
		id: "43",
		lastName: "Marzban",
		firstName: "Susan",
		phone: "4695937920",
		department: "ESL Aide",
		room: "A211",
		email: "Susan.Marzban@risd.org",
	},
	{
		id: "44",
		lastName: "Massey",
		firstName: "Gary",
		phone: "4695937946",
		department: "HUM",
		room: "A203",
		email: "Gary.Massey@risd.org",
	},
	{
		id: "45",
		lastName: "McCarthy",
		firstName: "Felicia",
		phone: "4695937954",
		department: "SpEd Res. Aide",
		room: "A208",
		email: "Felicia.McCarthy@risd.org",
	},
	{
		id: "46",
		lastName: "McLean",
		firstName: "Daney",
		phone: "4695938022",
		department: "AVID",
		room: "C104",
		email: "DaNey.McLean@risd.org",
	},
	{
		id: "47",
		lastName: "McThune",
		firstName: "Jamila",
		phone: "4695938040",
		department: "SPED Teacher",
		room: "A210",
		email: "Jamila.McThune@risd.org",
	},
	{
		id: "48",
		lastName: "Miguel",
		firstName: "Sheila",
		phone: "4695938043",
		department: "DP Aide",
		room: "B104",
		email: "Sheila.Miguel@risd.org",
	},
	{
		id: "49",
		lastName: "Morgan",
		firstName: "Kylah",
		phone: "4695937925",
		department: "PE/Coach",
		room: "SGYM",
		email: "Kylah.Morgan@risd.org",
	},
	{
		id: "50",
		lastName: "Muir",
		firstName: "Sarah",
		phone: "4695937950",
		department: "Theater",
		room: "A103",
		email: "Sara.Muir@risd.org",
	},
	{
		id: "51",
		lastName: "Myrick",
		firstName: "Katy",
		phone: "4695937962",
		department: "Science",
		room: "A215",
		email: "Katy.Myrick@risd.org",
	},
	{
		id: "52",
		lastName: "Nelson",
		firstName: "Jackie",
		phone: "4695937971",
		department: "Ani/Eng/Rob",
		room: "TECH",
		email: "Jack.Nelson@risd.org",
	},
	{
		id: "53",
		lastName: "Null",
		firstName: "Sherry",
		phone: "4695937926",
		department: "Science",
		room: "B101",
		email: "Sherry.Null@risd.org",
	},
	{
		id: "54",
		lastName: "Ontiveros",
		firstName: "Jesus",
		phone: "4695937952",
		department: "DP Aide",
		room: "B102",
		email: "Jesus.Ontiveros@risd.org",
	},
	{
		id: "55",
		lastName: "Parker",
		firstName: "Carina",
		phone: "4695938016",
		department: "Orchestra",
		room: "A111",
		email: "Carina.Parker@risd.org",
	},
	{
		id: "56",
		lastName: "Payne",
		firstName: "Laura",
		phone: "4695938003",
		department: "L-Z Counselor",
		room: "A121",
		email: "Laura.Payne@risd.org",
	},
	{
		id: "57",
		lastName: "Pernici",
		firstName: "Kristin",
		phone: "4695938032",
		department: "A-K AP",
		room: "OFFICE",
		email: "Kristin.Pernici@risd.org",
	},
	{
		id: "58",
		lastName: "Pippins",
		firstName: "Angela",
		phone: "4695938002",
		department: "A-K Counselor",
		room: "A121",
		email: "Angela.Pippins@risd.org",
	},
	{
		id: "59",
		lastName: "Pratt",
		firstName: "Stephanie",
		phone: "4695937988",
		department: "Math/DC",
		room: "B105",
		email: "Stephanie.Pratt@risd.org",
	},
	{
		id: "60",
		lastName: "Recinos",
		firstName: "Alan",
		phone: "4695937935",
		department: "Math/Coach",
		room: "B106",
		email: "Alan.Recinos@risd.org",
	},
	{
		id: "61",
		lastName: "Rivera",
		firstName: "Emily",
		phone: "4695937902",
		department: "ISS",
		room: "A109",
		email: "Emily.Rivera@risd.org",
	},
	{
		id: "62",
		lastName: "Robinson",
		firstName: "Meredith",
		phone: "4695937938",
		department: "HUM",
		room: "A212",
		email: "Meredith.Robinson@risd.org",
	},
	{
		id: "63",
		lastName: "Rodgers",
		firstName: "Marsha",
		phone: "4695937907",
		department: "AP Secretary",
		room: "OFFICE",
		email: "Marsha.Rodgers@risd.org",
	},
	{
		id: "64",
		lastName: "Rodriguez-Furlong",
		firstName: "Jessica",
		phone: "4695937946",
		department: "ESL",
		room: "A211",
		email: "Jessica.RodriguezFurlong@risd.org",
	},
	{
		id: "65",
		lastName: "Rogers",
		firstName: "Victoria",
		phone: "4695937905",
		department: "Attendance",
		room: "OFFICE",
		email: "Victoria.Rogers@risd.org",
	},
	{
		id: "66",
		lastName: "Rosales",
		firstName: "Chelsea",
		phone: "4695937972",
		department: "HUM",
		room: "A216",
		email: "Chelsea.Rosales@risd.org",
	},
	{
		id: "67",
		lastName: "Schwartz",
		firstName: "Shelly",
		phone: "4695937923",
		department: "Counselor",
		room: "A121",
		email: "Shelley.Schwarz@risd.org",
	},
	{
		id: "68",
		lastName: "Shirley",
		firstName: "Taylor M.",
		phone: "4695937908",
		department: "Nurse",
		room: "OFFICE",
		email: "Taylor.Shirley@risd.org",
	},
	{
		id: "69",
		lastName: "Sides",
		firstName: "Georgia",
		phone: "4695937951",
		department: "Science/ESL",
		room: "C101",
		email: "Georgia.Sides@risd.org",
	},
	{
		id: "70",
		lastName: "Smith",
		firstName: "Amy",
		phone: "4695937961",
		department: "Spanish",
		room: "A206",
		email: "Amy.Smith2@risd.org",
	},
	{
		id: "71",
		lastName: "Smith",
		firstName: "Shane",
		phone: "4695937927",
		department: "AVID/Coach",
		room: "C106",
		email: "Shane.Smith@risd.org",
	},
	{
		id: "72",
		lastName: "Soderberg",
		firstName: "Amy",
		phone: "4695937956",
		department: "HUM",
		room: "A219",
		email: "Amy.Soderberg@risd.org",
	},
	{
		id: "73",
		lastName: "Soto",
		firstName: "Luz",
		phone: "4695938034",
		department: "DP Aide",
		room: "A102",
		email: "Luz.Soto@risd.org",
	},
	{
		id: "74",
		lastName: "Strickland",
		firstName: "Matt",
		phone: "4695938026",
		department: "Bus./Coach",
		room: "A106",
		email: "Matt.Strickland@risd.org",
	},
	{
		id: "75",
		lastName: "Supan",
		firstName: "Anne",
		phone: "4695937932",
		department: "SPED DLC",
		room: "A101",
		email: "Annette.Supan@risd.org",
	},
	{
		id: "76",
		lastName: "Thomas",
		firstName: "Marcus",
		phone: "4695937922",
		department: "HUM",
		room: "A204",
		email: "Marcus.Thomas@risd.org",
	},
	{
		id: "77",
		lastName: "Tompkins",
		firstName: "Keith",
		phone: "4695938025",
		department: "HUM",
		room: "A105",
		email: "Keith.Tompkins@risd.org",
	},
	{
		id: "78",
		lastName: "Weak",
		firstName: "Andrew",
		phone: "4695938010",
		department: "Band",
		room: "BAND",
		email: "Andrew.Weak@risd.org",
	},
	{
		id: "79",
		lastName: "Wick",
		firstName: "Katherine",
		phone: "46959",
		department: "Choir",
		room: "CHOIR",
		email: "Katherine.Wick@risd.org",
	},
	{
		id: "80",
		lastName: "Young",
		firstName: "Esperanza",
		phone: "4695938023",
		department: "ICTS-SPED",
		room: "A209",
		email: "Esperanza.Young@risd.org",
	},
	{
		id: "81",
		lastName: "Young-Watkins",
		firstName: "Regina",
		phone: "4695937913",
		department: "IC HUM",
		room: "A108",
		email: "Regina.Young-Watkins@risd.org",
	},
	{
		id: "82",
		lastName: "Zackery",
		firstName: "Shataesia",
		phone: "4695937931",
		department: "DLC Aide",
		room: "A101",
		email: "Shataesia.Zackery@risd.org",
	},
];
